'use strict';
/* THE HERO FROM ITS SYNC RECORD (Owner, 26 Sep 2026). src/media/manifest.json (collection 001) (the Drive folder "000 - Hero Image", by file id)
 * → the Hero slides of index.html, between the HERO MEDIA markers. The first item is the frame itself (its poster or photograph
 * is the .am background, on screen at once, no script); the others are layers, in order. A video carries its file and whether
 * it has sound; the controls are the site's clip controls (Play / Pause · Sound on / Mute), shown by assets/hero-show.js only
 * on a video, the sound control only when that video has an audio track. No Drive id or URL reaches the page.
 *
 *   node src/build-hero.cjs            writes index.html
 *   node src/build-hero.cjs --check    exit 1 when index.html is not the record's */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
/* the Hero is collection 001 of the site-wide media contract (src/media/manifest.json — the Media Asset Agent) */
const REC = Object.assign({ collection: '' }, JSON.parse(fs.readFileSync(path.join(ROOT, 'src', 'media', 'manifest.json'), 'utf8')).collections['001']);
REC.collection = REC.title.trim();
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '<!-- HERO MEDIA:BEGIN', END = '<!-- HERO MEDIA:END -->';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const fp = (f) => '--fp-p:' + f.p + ';--fp-tp:' + f.tp + ';--fp-tl:' + f.tl + ';--fp-d:' + f.d;
const still = (x) => (x.kind === 'video' ? x.poster : x.asset);
/* a film is served by the Worker's byte-range route (/media/<name>.mp4 → assets/video/<name>.mp4): Safari needs 206 answers */
const filmUrl = (x) => 'media/' + path.basename(x.asset);
const media = (x) => (x.kind === 'video' ? ' data-hero-video="' + esc(filmUrl(x)) + '" data-audio="' + (x.audio ? 1 : 0) + '"' : '');

function render() {
  const [first, ...rest] = REC.items;
  const out = [];
  out.push('<!-- HERO MEDIA:BEGIN · generated by src/build-hero.cjs from src/media/manifest.json (collection 001) (the Drive collection "' + REC.collection + '", ' + REC.items.length + ' items, by file id) — do not edit by hand -->');
  out.push('    <div class="am" style="background-image:url(' + esc(still(first)) + ');' + fp(first.focal) + '" role="img" aria-label="' + esc(first.alt || '') + '" data-hero-show' + media(first) + '>');
  for (const x of rest) out.push('      <span class="a-hero-slide" data-src="' + esc(still(x)) + '"' + media(x) + ' style="' + fp(x.focal) + '" aria-hidden="true"></span>');
  out.push('    </div>');
  out.push('    <div class="a-hero-ctl" data-hero-ctl hidden>' +
    '<button type="button" class="a-clip-btn" data-hero-play aria-label="Play the film"><i class="ic-play" aria-hidden="true"></i><i class="ic-pause" aria-hidden="true"></i><span class="t">Play</span></button>' +
    '<button type="button" class="a-clip-btn" data-hero-sound aria-label="Sound on" hidden><i class="ic-sound" aria-hidden="true"></i><span class="t">Sound on</span></button></div>');
  out.push('    ' + END);
  return out.join('\n');
}
function problems() {
  const p = [];
  const seen = new Set();
  REC.items.forEach((x, i) => {
    if (!x.driveId || seen.has(x.driveId)) p.push('item ' + i + ': a missing or repeated Drive id'); seen.add(x.driveId);
    if (!/^(image|video)$/.test(x.kind)) p.push(x.title + ': kind must be image or video');
    for (const f of [x.asset, x.kind === 'video' ? x.poster : null].filter(Boolean)) if (!fs.existsSync(path.join(ROOT, f))) p.push(x.title + ': ' + f + ' is missing');
    if (x.kind === 'video' && !/^assets\/video\/[a-z0-9-]+\.mp4$/.test(x.asset)) p.push(x.title + ': a film lives in assets/video/ as <name>.mp4 (the /media/ route)');
    if (x.kind === 'video' && typeof x.audio !== 'boolean') p.push(x.title + ': a video states whether it has sound');
    if (!x.focal || !['p', 'tp', 'tl', 'd'].every((k) => /^\d+% \d+%$/.test(x.focal[k] || ''))) p.push(x.title + ': four focal points');
  });
  const titles = REC.items.map((x) => x.title);
  /* the order is the Drive titles unless the record states an explicit, Owner-set order (orderNote says whose and why) */
  if (REC.order === 'title-ascending' && titles.join('\n') !== titles.slice().sort().join('\n')) p.push('the items are not in Drive title order');
  if (REC.order === 'explicit' && !REC.orderNote) p.push('an explicit order names its reason (orderNote)');
  if (!REC.items[0] || !REC.items[0].alt) p.push('the first item needs its alt text');
  return p;
}
const html = fs.readFileSync(INDEX, 'utf8');
const a = html.indexOf(BEGIN), b = html.indexOf(END);
if (a < 0 || b < 0) { console.error('index.html has no HERO MEDIA markers'); process.exit(1); }
const next = html.slice(0, a) + render() + html.slice(b + END.length);
const bad = problems();
if (bad.length) { console.error('media manifest · collection 001: ' + bad.join(' · ')); process.exit(1); }
if (process.argv.includes('--check')) {
  if (next !== html) { console.error('index.html is not the Hero of src/media/manifest.json (collection 001) — run node src/build-hero.cjs'); process.exit(1); }
  console.log('hero: ' + REC.items.length + ' items (' + REC.items.filter((x) => x.kind === 'video').length + ' video) · index.html current');
} else { fs.writeFileSync(INDEX, next); console.log('hero: index.html written from ' + REC.items.length + ' items'); }
