/* Builds the locale layer: src/i18n-core.js + src/i18n-runtime.js → assets/i18n/siyl-i18n.js, and the authored Thai dictionary
 * src/i18n-th.json → assets/i18n/th.js. Run after any change to those sources: node src/build-i18n.cjs */
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const R = path.join(__dirname, '..');
const h = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 8);
const dict = JSON.parse(fs.readFileSync(path.join(__dirname, 'i18n-th.json'), 'utf8'));
const thJs = '/* GENERATED by src/build-i18n.cjs from src/i18n-th.json — do not edit. The authored Thai of the site. */\nwindow.SIYL_TH = ' + JSON.stringify(dict) + ';\n';
fs.writeFileSync(path.join(R, 'assets/i18n/th.js'), thJs);
fs.writeFileSync(path.join(__dirname, 'i18n-th.dict.js'), '/* GENERATED by src/build-i18n.cjs from src/i18n-th.json — the Thai dictionary for the Worker (guest email). */\nexport default ' + JSON.stringify(dict) + ';\n');
const thCss = fs.readFileSync(path.join(R, 'assets/i18n/th.css'), 'utf8');
const core = fs.readFileSync(path.join(__dirname, 'i18n-core.js'), 'utf8');
const rt = fs.readFileSync(path.join(__dirname, 'i18n-runtime.js'), 'utf8').replace('__TH_JS__', h(thJs)).replace('__TH_CSS__', h(thCss));
fs.writeFileSync(path.join(R, 'assets/i18n/siyl-i18n.js'), '/* GENERATED by src/build-i18n.cjs from src/i18n-core.js + src/i18n-runtime.js — do not edit. */\n' + core + '\n' + rt);
console.log('i18n: ' + Object.keys(dict.exact || {}).length + ' exact · ' + (dict.templates || []).length + ' templates · ' + (dict.keep || []).length + ' kept · th.js ' + Buffer.byteLength(thJs) + ' B');
