'use strict';
/* Source-driven localization catalog (HSW-001 P0 §2/§5/§8):
 * extracts EVERY guest-facing text node from the public + Guest Area HTML.
 * The catalog defines the REQUIRED translation scope — the release gate
 * fails when any entry is neither translated nor pattern-localizable. */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const WHITELIST = /^([·\s]*((Souphattra Heritage )?Vientiane|Special Express No\. 25)$)|^(Haruthai|Suthep|Peggy|Steffie|Souphattra|Vientiane|Bangkok|Nong Khai|Kunming|Lijiang|Laos|Mekong|Krung Thep|Wat |LINE|WhatsApp|Wattay|Sinh|Kip|LAK|USD|THB|EUR|JA|TH|DE|EN|SRT|No\. 25|Jaguar|Mercedes|Kempinski|Sathorn|Wanxiang|Luye|Khun|The Heritage|Heritage (Executive|Grand Premier)|Noble Courtyard|Grand Majestic|Souphattra (Majestic|Presidential)|guest\.relation|seeyouinlaos|[0-9·:.,'’\s\-–—/+()&%#!?]*$)/;
function extract(file) {
  let s = fs.readFileSync(path.join(ROOT, file), 'utf8');
  s = s.replace(/<script[\s\S]*?<\/script>/g, ' ').replace(/<style[\s\S]*?<\/style>/g, ' ');
  const out = new Set();
  for (const m of s.matchAll(/(?:aria-label|placeholder|title)="([^"]+)"/g)) {
    let t = m[1].replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
    if (t.length >= 2 && !WHITELIST.test(t) && /[A-Za-z]{2}/.test(t)) out.add(t);
  }
  for (const m of s.matchAll(/>([^<>]+)</g)) {
    let t = m[1].replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ').replace(/&quot;/g, '"').replace(/&#39;|&rsquo;/g, '’').replace(/&middot;/g, '·').replace(/\s+/g, ' ').trim();
    if (t.length < 2 || WHITELIST.test(t) || !/[A-Za-z]{2}/.test(t)) continue;
    out.add(t);
  }
  return out;
}
const cat = new Set([...extract('index.html'), ...extract('register/index.html')]);
const list = [...cat].sort();
fs.writeFileSync(path.join(ROOT, 'assets/i18n/catalog.js'),
  '/* generated by src/i18n-catalog.cjs — DO NOT EDIT BY HAND */\nwindow.SIYL_CATALOG = ' + JSON.stringify(list) + ';\n');
console.log('catalog:', list.length, 'required guest-facing strings');
