/* GENERATED by src/build-media-sizes.cjs — the byte size of every film under assets/video/ (the /media byte-range route). */
export const MEDIA_SIZES = {
 "bangkok-main.mp4": 4788795,
 "baron-01.mp4": 2991180,
 "baron-02.mp4": 4602428,
 "baron-03.mp4": 5101337,
 "cannubi-card.mp4": 2083223,
 "chapter-after.mp4": 4481621,
 "chapter-before.mp4": 14627977,
 "chapter-wedding.mp4": 920519,
 "destinations-hero.mp4": 4550663,
 "hero-000-main.mp4": 8189370,
 "hero-000.mp4": 2245140,
 "kunming-card.mp4": 5834536,
 "lijiang-main-01.mp4": 8373199,
 "lijiang-main-02.mp4": 2669544,
 "lijiang-main-03.mp4": 1487335,
 "lijiang-main-04.mp4": 1097494,
 "lijiang-main-05.mp4": 3141973,
 "vientiane-card.mp4": 2856658,
 "vientiane-journey-card-hevc.mp4": 18900843,
 "vientiane-journey-card.mp4": 24817973
};
