#!/usr/bin/env python3
"""008 — COPY AUDIT · the wording changes, as one deterministic replacement table (WORDING-CONTRACT.md).
Facts, prices, times, inventory rules and logic are untouched; every replacement is an exact string swap and
the script refuses to run if any expected string is missing. Re-runnable (a second run finds nothing to do).
  python3 docs/review/008-copy-audit/apply.py
"""
import glob, os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
HTML = sorted(glob.glob(os.path.join(ROOT, '*.html')))
def rel(p): return os.path.relpath(p, ROOT)
changed = {}
def sub(path, old, new, min_count=1, files=None):
    paths = files or [path]
    total = 0
    for p in paths:
        p = p if os.path.isabs(p) else os.path.join(ROOT, p)
        s = open(p, encoding='utf8').read(); n = s.count(old)
        if n: open(p, 'w', encoding='utf8').write(s.replace(old, new)); changed[rel(p)] = changed.get(rel(p), 0) + n
        total += n
    if total < min_count and not RERUN: sys.exit('MISSING: %r in %s' % (old, [rel(x) for x in paths]))
    return total
RERUN = '--rerun' in sys.argv

# ---- A · the header bag icon and the public → private CTAs (T-01, T-02)
sub(None, 'aria-label="Your Journey"', 'aria-label="My Bag"', files=HTML)
sub(None, 'aria-label="Your bag"', 'aria-label="My Bag"', files=HTML)
sub(None, 'data-cta-in="Continue Your Journey"', 'data-cta-in="Open My Trip"', files=HTML)
sub('assets/aman.js', "['Your Journey', 'your-journey.html', null]", "['My Trip', 'your-journey.html', null]")
sub('invitation.html', 'Continue to Your Journey</button>', 'Continue to My Trip</button>')
sub('invitation.html', 'Open your invitation and your private journey begins — your name, your travel, the wedding day.', 'Open your invitation and your private trip begins — your name, your travel, the wedding day.')
sub('invitation.html', 'Everything on this website — your journey, the wedding day, your preferences — belongs to it', 'Everything on this website — your trip, the wedding day, your preferences — belongs to it')
sub('invitation.html', 'Your private journey: your travel, the wedding day and the details that help us take care of you along the way — all in one place.', 'Your travel, the wedding day and the details that help us take care of you along the way — all in one place.')
sub('assets/prep-shell.js', "'<p class=\"prep-eyebrow\">Your private journey</p>'", "'<p class=\"prep-eyebrow\">Private</p>'", min_count=2)

# ---- B · adding and removing a product names the Bag (T-03)
sub('journeys.html', '>Add to Your Journey</button>', '>Add to My Bag</button>', min_count=3)
sub('journeys.html', "'Remove from Your Journey':'Add to Your Journey'", "'Remove from My Bag':'Add to My Bag'")
sub('journeys.html', "'Add to Your Journey')", "'Add to My Bag')")
sub('journeys.html', "'Selected for your journey'", "'Selected · in My Bag'")
sub('journeys.html', "it replaces '+room+' in your journey; nothing else changes.", "it replaces '+room+' in your trip; nothing else changes.")
sub('journeys.html', 'The trip, chapter by chapter. Rooms, fares, seats and tickets are chosen inside your invitation', 'The journey, chapter by chapter. Rooms, fares, seats and tickets are chosen inside your invitation')
sub('journeys.html', "'Save '+P.money(275-c.price)+' pp'", "P.money(275-c.price)+' less per person'")
sub('your-journey.html', "'Save '+P.money(275-c.price)+' per person'", "P.money(275-c.price)+' less per person'")
sub('room.html', '>Add to Your Journey</button>', '>Add to My Bag</button>', min_count=2)
sub('room.html', "b.textContent = 'Remove from Your Journey';", "b.textContent = 'Remove from My Bag';")
sub('room.html', "b.textContent = 'Add to Your Journey';", "b.textContent = 'Add to My Bag';")
sub('room.html', "swap.textContent = 'Your journey currently holds '", "swap.textContent = 'Your trip currently holds '")
sub('transport.html', "'<button class=\"cta\" id=\"add\">Add to Your Journey</button>'", "'<button class=\"cta\" id=\"add\">Add to My Bag</button>'")
sub('transport.html', "has ? 'Remove from Your Journey' : 'Add to Your Journey'", "has ? 'Remove from My Bag' : 'Add to My Bag'")
sub('transport.html', 'In your journey · <a href="your-journey.html">View</a> · <a href="cart.html">Your bag</a>', 'In My Bag · <a href="your-journey.html">Open My Trip</a> · <a href="cart.html">Open My Bag</a>')
sub('tea.html', '>Add to Your Journey</button>', '>Add to My Bag</button>')
sub('tea.html', 'Just added to your journey', 'Added to My Bag')
sub('tea.html', 'href="your-journey.html">View Your Journey</a>', 'href="cart.html">Open My Bag</a>')
sub('experience.html', '<p class="a-eyebrow">Your Journey</p>', '<p class="a-eyebrow">My Bag</p>')
sub('experience.html', "places a restaurant request in your journey for the guests who take part; Guest Relations arrange the table through your journey. It is a request — not a confirmed reservation, and availability is not guaranteed by this page.", "places a restaurant request in your bag for the guests who take part; Guest Relations arrange the table. It is a request, not a reservation — availability is not guaranteed by this page.")
sub('experience.html', '<a class="a-link" href="cart.html">View your bag</a>', '<a class="a-link" href="cart.html">Open My Bag</a>')
sub('experience.html', 'Remove from your journey</button>', 'Remove from My Bag</button>')
sub('experience.html', "Add to your journey · ' + money(s.price)", "Add to My Bag · ' + money(s.price)")
sub('experiences.html', 'One table, Sühring, can be asked for through your journey.', 'One table, Sühring, can be asked for through My Bag.')
sub('experiences.html', 'you can add to your Journey Bag', 'you can add to My Bag', min_count=2)
sub('experiences.html', 'we will arrange it with the spa — it carries no journey cost.', 'we will arrange it with the spa — it is not part of your total.')
sub('wedding.html', "' · in your journey</p>'", "' · in My Bag</p>'")
sub('assets/travelpass.js', "selected: 'Selected · in your journey'", "selected: 'Selected · in My Bag'")
sub('assets/travelpass.js', "'Not in your journey'", "'Not in My Bag'")
sub('assets/travelpass.js', 'Guest Relations has received your journey.', 'Guest Relations has received your trip.')
sub('assets/travelpass.js', 'If you change your journey, download this pass again', 'If you change your trip, download this pass again')
sub('accommodation.html', 'See the stays in your journey</a>', 'See the stays along The Journey</a>')

# ---- C · the private plan is "your trip" (T-05, T-07, T-08, T-09)
sub('cart.html', '<p class="t-l1" id="cart-own">Your bag</p>', '<p class="t-l1" id="cart-own">My Bag</p>')
sub('cart.html', 'Change or remove anything here; your journey and Review &amp; Send follow at once.', 'Change or remove anything here; your trip and Review &amp; Send follow at once.')
sub('cart.html', 'href="review.html">Review your journey</a>', 'href="review.html">Review &amp; Send</a>')
sub('cart.html', 'Your journey is not ready to review yet', 'Not ready for Review &amp; Send yet')
sub('cart.html', "href=\"'+first.href+'\">Complete this</a>", "href=\"'+first.href+'\">Complete this step</a>")
sub('cart.html', "ready.ok?'Review your journey':'Complete this first'", "ready.ok?'Review & Send':'Complete this first'")
sub('about-you.html', 'Two documents help us coordinate your journey.', 'Two documents help us coordinate your trip.')
sub('about-you.html', 'Your journey can still be sent — Guest Relations will ask you for this directly.', 'Your trip can still be sent — Guest Relations will ask you for this directly.')
sub('dress.html', '<p class="dreq">In your private journey</p>', '<p class="dreq">In My Trip</p>')
sub('dress.html', 'Wedding Preparation of your private journey. It is never ticked for you, and your journey cannot be sent', 'Wedding Preparation of My Trip. It is never ticked for you, and your trip cannot be sent')
sub('dress.html', 'Continue in your private journey</a>', 'Continue in My Trip</a>')
sub('voyage.html', 'hosted for every guest — part of your journey, never a charge.', 'hosted for every guest — part of your trip, never a charge.')
sub('voyage.html', 'you will find it in your private journey</a>', 'you will find it in My Trip</a>')
sub('voyage.html', '<p class="a-eyebrow">Your private journey</p>', '<p class="a-eyebrow">My Trip</p>')
sub('voyage.html', 'Those answers are made inside your own private journey, where they are kept by name.', 'Those answers are made inside My Trip, where they are kept by name.')
sub('voyage.html', 'href="wedding.html">Open your private journey</a>', 'href="wedding.html">Open My Trip</a>')
sub('marsilea.html', 'nothing here is a booked time, and spa treatments are not part of your journey costs.', 'nothing here is a booked time, and spa treatments are not part of your total.')
sub('tickets.html', 'Every ticket of your journey, exactly as it stands', 'Every ticket of your trip, exactly as it stands')
sub('tickets.html', "'Reading the seating ledger…'", "'Reading your seats…'")
sub('tickets.html', 'Your seat tickets appear here the moment a seat is confirmed.', 'Your seat tickets appear here the moment a seat is held in your name.')
sub('tickets.html', '<p class="t-l1">Your journey · 21 February – 8 March 2027</p>', '<p class="t-l1">Your trip · 21 February – 8 March 2027</p>')
sub('tickets.html', 'No transport is in your journey yet.', 'No transport is in your trip yet.')
sub('tickets.html', 'href="your-journey.html">Go to Your Journey</a>', 'href="your-journey.html">Open My Trip</a>')
sub('tickets.html', 'A seat ticket shows your seat exactly as the seating ledger holds it.', 'A seat ticket shows your seat exactly as it is held for you.')
sub('your-journey.html', 'aria-label="Your journey, in order"', 'aria-label="Your trip, in order"')
sub('your-journey.html', '<h2 class="t-h2">Also in your journey</h2>', '<h2 class="t-h2">Also in your trip</h2>')
sub('your-journey.html', 'The hosted wedding day is part of your journey without charge. A spa interest carries no journey cost — paid directly at the spa.', 'The hosted wedding day is part of your trip without charge. A spa interest is not part of your total — it is paid directly at the spa.')
sub('your-journey.html', "P.money(q.total)+'<span class=\"t-l1\">total per person · your cost</span>", "P.money(q.total)+' <span class=\"t-l1\">total per person · your cost</span>")
sub('your-journey.html', 'id="fxb">Complete journey<span>All ten stages, selected for you</span>', 'id="fxb">Complete trip<span>All ten stages, selected for you</span>')
sub('your-journey.html', 'id="csb">Essential journey</button>', 'id="csb">Essential trip</button>')
sub('your-journey.html', '<p class="t-l1 on">Your journey is ready</p>', '<p class="t-l1 on">Your trip is ready</p>')
sub('your-journey.html', "'Each stage is arranged with us. Review &amp; Send shares your journey with Guest Relations.'", "'Every stage is chosen. Review &amp; Send shares your trip with Guest Relations.'")
sub('your-journey.html', 'Start with our suggested journey</h2>', 'Start with our suggested trip</h2>')
sub('your-journey.html', 'or let the journey complete itself, and change any stage afterwards.', 'or let the trip complete itself, and change any stage afterwards.')
sub('your-journey.html', "(cost?'Essential journey':'Complete journey')", "(cost?'Essential trip':'Complete trip')")
sub('your-journey.html', "'Complete the remaining journey.'", "'Complete the remaining trip.'")
sub('your-journey.html', 'The complete journey fills only the stages that are still open', 'The complete trip fills only the stages that are still open')
sub('your-journey.html', "'Add the complete journey'", "'Add the complete trip'")
sub('your-journey.html', "is no longer available, so your journey has not been changed", "is no longer available, so your trip has not been changed")
sub('assets/journey.js', "return 'Your journey is ready.';", "return 'Your trip is ready.';")
sub('assets/guest.js', "label: 'Send your journey to Guest Relations'", "label: 'Send your trip to Guest Relations'")
sub('assets/draft.js', "'Save failed · try again'", "'Not saved · try again'")

# ---- D · Review & Send (T-05, D-02, X-02, M-01)
sub('review.html', '<p class="t-l1" id="rv-own">Your journey · nothing is paid on this website</p>', '<p class="t-l1" id="rv-own">My Trip · nothing is paid on this website</p>')
sub('review.html', 'A spa interest carries no journey cost — paid directly at the spa.', 'A spa interest is not part of your total — it is paid directly at the spa.')
sub('review.html', '<i class="prep-tick" aria-hidden="true"></i> Received</p><h2 class="t-h1" id="sent-h">Your journey has been received by Guest Relations</h2>', '<i class="prep-tick" aria-hidden="true"></i> Received · under review</p><h2 class="t-h1" id="sent-h">Your trip has been received by Guest Relations</h2>')
sub('review.html', 'Sending shares your journey with Guest Relations so a person can look at it.', 'Sending shares your trip with Guest Relations so a person can look at it.')
sub('review.html', '<b>Received</b> means your journey is safely with Guest Relations.', '<b>Received</b> means your trip is safely with Guest Relations.')
sub('review.html', 'nothing in your journey is final.', 'nothing in your trip is final.')
sub('review.html', 'id="again">Change my journey and send again</button>', 'id="again">Change and send again</button>')
sub('review.html', "'✓ Journey saved'", "'✓ Trip saved'")
sub('review.html', "'✓ Updated journey sent to Guest Relations'", "'✓ Updated trip sent to Guest Relations'")
sub('review.html', "l.textContent=upd?'Updated journey sent':'Confirmation email sent'", "l.textContent=upd?'Updated trip sent':'Confirmation email sent'")
sub('review.html', "l.textContent='Your journey is saved';", "l.textContent='Your trip is saved';")
sub('review.html', "'We have your journey. Guest Relations will review your selections personally.", "'We have your trip. Guest Relations will review your selections personally.", min_count=2)
sub('review.html', "btn.textContent=upd?'Send updated journey':", "btn.textContent=upd?'Send Updated Trip':")
sub('review.html', "b.textContent!=='Send updated journey'", "b.textContent!=='Send Updated Trip'")
sub('review.html', "el.innerHTML='<b>Your journey</b> · saved as draft'", "el.innerHTML='<b>My Trip</b> · saved as draft'")
sub('review.html', "'Could not prepare — try again'", "'Could not prepare the ticket — try again'")
sub('wedding.html', "'Could not prepare — try again'", "'Could not prepare the ticket — try again'")
sub('wedding-preparation.html', "'Could not prepare — try again'", "'Could not prepare the ticket — try again'")
sub('review.html', 'Your documents are used only to help us coordinate your journey,', 'Your documents are used only to help us coordinate your trip,')
sub('review.html', '<h3 class="t-h1">Your journey can be sent</h3>', '<h3 class="t-h1">Your trip can be sent</h3>')
sub('review.html', 'Your journey is sent under your own invitation, so we open it first.', 'Your trip is sent under your own invitation, so we open it first.')
sub('review.html', 'it never delays your journey.', 'it never delays your trip.')
sub('review.html', 'A few steps above are still needed before your journey can be sent.', 'A few steps above are still needed before your trip can be sent.')
sub('review.html', '<p class="t-l1 on">We have your journey</p><h2 class="t-h1">Guest Relations has your journey</h2>', '<p class="t-l1 on">We have your trip</p><h2 class="t-h1">Guest Relations has your trip</h2>')
sub('review.html', 'Guest Relations holds the journey sent on ', 'Guest Relations holds the trip sent on ')
sub('review.html', '<p class="t-l1 open">Your journey has changed</p>', '<p class="t-l1 open">Your trip has changed</p>')
sub('review.html', '<p class="t-l1 on">Your journey is confirmed</p>', '<p class="t-l1 on">Your trip is confirmed</p>', min_count=2)
sub('review.html', 'Something in your journey has been changed on this device', 'Something in your trip has been changed on this device')
sub('review.html', "'SEE YOU IN LAOS — JOURNEY SELECTION'", "'SEE YOU IN LAOS — MY TRIP'")
sub('review.html', 'subject=Journey%20Selection%20', 'subject=My%20Trip%20', min_count=0)
sub('review.html', 'not a confirmed reservation)', 'not a reservation)')
sub('review.html', "' · INTEREST ONLY (no journey cost, payable at the spa)'", "' · INTEREST ONLY (not part of your total, payable at the spa)'")
sub('review.html', "L.push('','SEATS (as the ledger holds them):');", "L.push('','SEATS:');")
sub('review.html', "cs?'seat '+Lx.label(cs)+' ('+cs+')':'none'", "cs?'seat '+Lx.label(cs):'none'")
sub('review.html', "ds?'seat '+Lx.label(ds)+' ('+ds+')':'none'", "ds?'seat '+Lx.label(ds):'none'")
sub('review.html', "' ('+x.filename+', '+x.receivedAt+', sha256 '+x.sha256.slice(0,16)+'…)'", "' ('+x.filename+', received '+when(x.receivedAt)+')'")
sub('review.html', "' ('+g.publicationAt+', wording '+g.publicationVersion+')'", "' ('+when(g.publicationAt)+')'")
sub('review.html', "'acknowledged '+gr.guests[0].dress.at+' (text version '+gr.guests[0].dress.textVersion+')'", "'acknowledged '+when(gr.guests[0].dress.at)")
sub('review.html', "'acknowledged '+gr.photo.at+' (text version '+gr.photo.textVersion+')'", "'acknowledged '+when(gr.photo.at)")
sub('review.html', "L.push('Submitted via Review & Send · '+new Date().toISOString());", "L.push('Sent via Review & Send · '+when(new Date().toISOString()));")
sub('review.html', "'HELD — places held in the guest\\'s own name in the room engine, not a confirmed booking'", "'HELD — places held in your name, not yet confirmed'")
sub('review.html', "'UNKNOWN — room engine not read on this device'", "'UNKNOWN — rooms not read on this device'")

# ---- E · availability, reservation and confirmation words (S-01 … S-06)
sub('assets/rooms.js', "return 'Fully booked';", "return 'Sold out';", min_count=2)
sub('journeys.html', "||'Fully booked')", "||'Sold out')")
sub('room.html', "|| 'Fully booked';", "|| 'Sold out';")
sub('assets/stay.js', "' — not bookable through the website.'", "' — not available through the website.'")
sub('assets/rooms-data.js', "'Complimentary — USD 0 payable by you. Up to six guests in total, and the ledger holds the places live.'", "'Complimentary — nothing to pay. Up to six guests in total; places are held as they are taken.'")
sub('assets/journey.js', "basis: 'Interest · confirmed and payable at the spa'", "basis: 'Interest · Marsilea Spa confirms the time · payable at the spa'")
sub('assets/pricing.js', "return 'Interest · confirmed and payable at the spa';", "return 'Interest · Marsilea Spa confirms the time · payable at the spa';")
sub('assets/pricing.js', "a table requested through Guest Relations · not a confirmed reservation'", "a table requested through Guest Relations · a request, not a reservation'")
sub('wedding-preparation.html', 'The dress code is understood once, here, and confirmed once — in your own name.', 'The dress code is understood once, here, and acknowledged once — in your own name.')
sub('wedding-preparation.html', "(fixed?'Front centre':'Confirmed')", "(fixed?'Front centre':'Held in your name')")
sub('wedding-preparation.html', "Seat confirmed</p><h3 class=\"t-h1\">Your '+ev+' seat is confirmed</h3>", "Seat held</p><h3 class=\"t-h1\">Your '+ev+' seat is held in your name</h3>")
sub('wedding-preparation.html', "S.frozen()?'Seat allocated':'Seat confirmed'", "S.frozen()?'Seat allocated':'Seat held'")
sub('wedding-preparation.html', "(fresh?'Seat confirmed':'')", "(fresh?'Seat held':'')")
sub('wedding-preparation.html', "setAttribute('aria-label','Booking summary')", "setAttribute('aria-label','Your seat')")
sub('wedding-preparation.html', "(change?'Change of seat':'Booking summary')", "(change?'Change of seat':'Your seat')")
sub('assets/seatpass.js', "return s.fixed ? 'FRONT CENTRE' : 'CONFIRMED';", "return s.fixed ? 'FRONT CENTRE' : 'HELD';")
sub('assets/seatpass.js', 'This ticket shows your seat exactly as Guest Relations hold it in the seating ledger at the time of download.', 'This ticket shows your seat exactly as Guest Relations hold it at the time of download.')
sub('assets/seatpass.js', "e(s.fixed ? 'Front centre' : 'Confirmed')", "e(s.fixed ? 'Front centre' : 'Held in your name')", min_count=2)

# ---- F · the emails (T-06)
M = 'src/mail-templates.js'
sub(M, "'Your Journey has been updated — ' : 'Your Journey has been received — '", "'Your trip has been updated — ' : 'Your trip has been received — '")
sub(M, "h1(M.upd ? 'Your journey has been updated' : 'Your journey has been received')", "h1(M.upd ? 'Your trip has been updated' : 'Your trip has been received')")
sub(M, "'Thank you — your journey has reached Guest Relations.", "'Thank you — your trip has reached Guest Relations.")
sub(M, 'This updated journey replaces the previous version for review.', 'This updated trip replaces the previous version for review.')
sub(M, 'is a personal offering and not part of the journey cost.', 'is a personal offering and not part of your trip cost.', min_count=2)
sub(M, "button(SITE + '/invitation', 'Open your journey')", "button(SITE + '/invitation', 'Open My Trip')")
sub(M, "T.push('SEE YOU IN LAOS — YOUR JOURNEY', '', M.upd ? 'Your journey has been updated' : 'Your journey has been received'", "T.push('SEE YOU IN LAOS — MY TRIP', '', M.upd ? 'Your trip has been updated' : 'Your trip has been received'")
sub(M, "T.push('Open your journey: ' + SITE + '/invitation'", "T.push('Open My Trip: ' + SITE + '/invitation'")
sub(M, "label('Updated journey')", "label('Updated trip')")
sub(M, "M.upd ? 'Updated journey' : 'Initial submission'", "M.upd ? 'Updated trip' : 'Initial submission'", min_count=2)

sub(M, "esc(eyebrow || 'Your journey')", "esc(eyebrow || 'My Trip')")
sub(M, "(M.upd ? 'Journey updated — ' : 'Journey received — ') + M.fullName", "(M.upd ? 'Trip updated — ' : 'Trip received — ') + M.fullName")
sub(M, "h1(M.upd ? 'Journey updated' : 'New journey received')", "h1(M.upd ? 'Trip updated' : 'New trip received')")
sub(M, "M.upd ? 'Journey updated' : 'New journey received', ''", "M.upd ? 'Trip updated' : 'New trip received', ''")

sub(M, "kvRow('Guest', M.fullName + (M.guestId ? ' · ' + M.guestId : ''))", "kvRow('Guest', M.fullName)")

sub(M, "T.push('Guest: ' + M.fullName + (M.guestId ? ' · ' + M.guestId : ''),", "T.push('Guest: ' + M.fullName,")
sub('cart.html', '<title>Your Bag · See You In Laos</title>', '<title>My Bag · See You In Laos</title>')
sub('your-journey.html', '<title>Your Journey · See You In Laos</title>', '<title>My Trip · See You In Laos</title>')

sub('about-you.html', '<title>About you · See You In Laos</title>', '<title>My Profile · See You In Laos</title>')

sub('review.html', 'Your confirmed journey', 'Your confirmed trip')

sub('journeys.html', 'Your journey stays exactly as it is — the new room', 'Your trip stays exactly as it is — the new room')
sub('review.html', '<div class="p-block-h"><h2>Your journey</h2>', '<div class="p-block-h"><h2>My Trip</h2>')
sub('review.html', '<b>Your journey</b> · saved as draft</p>', '<b>My Trip</b> · saved as draft</p>')
sub('review.html', 'Your journey stays saved — try once more in a moment', 'Your trip stays saved — try once more in a moment')
sub('review.html', 'Your journey could not be saved just now', 'Your trip could not be saved just now')

sub('review.html', "dm.textContent='We have your trip. Guest Relations will review your selections personally. Nothing is confirmed yet; we will confirm each arrangement with you once it is ready.'", "dm.textContent='Nothing more is needed from you now.'")
sub('review.html', 'this device cannot tell which version it was.', 'this device cannot tell which copy it was.')

print('files changed:', len(changed)); [print('  %-28s %d' % (k, v)) for k, v in sorted(changed.items())]
