#!/usr/bin/env python3
"""008 — COPY AUDIT · the test pins that encoded the retired wording, moved to the canonical words (same assertions, new strings)."""
import os, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
P = [
 ('test/access.test.mjs', 'Add to Your Journey<\\/button>', 'Add to My Bag<\\/button>'),
 ('test/efg.test.mjs', '/We have your journey/', '/We have your trip/'),
 ('test/eligibility.test.mjs', r"not bookable through the website\.'", r"not available through the website\.'"),
 ('test/emergency-live.test.mjs', '/Journey received — Peggy Berger · SYL-G001-/', '/Trip received — Peggy Berger · SYL-G001-/'),
 ('test/emergency-live.test.mjs', "l\\.textContent='Your journey is saved';", "l\\.textContent='Your trip is saved';"),
 ('test/experiences.test.mjs', 'not a confirmed reservation\\)', 'not a reservation\\)'),
 ('test/experiences.test.mjs', 'not a confirmed reservation, and availability is not guaranteed by this page', 'not a reservation — availability is not guaranteed by this page'),
 ('test/flow.test.mjs', '/Review your journey/', '/Review (&amp;|&) Send/'),
 ('test/inventory.test.mjs', '/The complete journey/', '/The complete trip/'),
 ('test/journey-draft.test.mjs', 'Journey received — Sam Example', 'Trip received — Sam Example'),
 ('test/journey-draft.test.mjs', 'Journey updated — Sam Example', 'Trip updated — Sam Example'),
 ('test/journey-draft.test.mjs', "/'Save failed · try again'/", "/'Not saved · try again'/"),
 ('test/mail-ci.test.mjs', "'Your Journey has been received — SYL-G777-34DBEFD3'", "'Your trip has been received — SYL-G777-34DBEFD3'"),
 ('test/mail-ci.test.mjs', "'Your Journey has been updated — SYL-G777-34DBEFD3'", "'Your trip has been updated — SYL-G777-34DBEFD3'"),
 ('test/mail-ci.test.mjs', '/New journey received/', '/New trip received/'),
 ('test/owner-patch-003.test.mjs', 'Right block · row 4\\nCONFIRMED$/', 'Right block · row 4\\nHELD$/'),
 ('test/pricing.test.mjs', '/Change my journey and send again/', '/Change and send again/'),
 ('test/real-guest-mail.test.mjs', '/Journey received — Sam Example · SYL-G777-/', '/Trip received — Sam Example · SYL-G777-/'),
 ('test/real-guest-mail.test.mjs', "/'✓ Journey saved'/", "/'✓ Trip saved'/"),
 ('test/recompose.test.mjs', '/Continue to Your Journey/', '/Continue to My Trip/'),
 ('test/seating-labels.test.mjs', '/Seat confirmed/', '/Seat held/'),
 ('test/travelpass.test.mjs', "'Selected · in your journey'", "'Selected · in My Bag'"),
 ('test/travelpass.test.mjs', '/Selected · in your journey/', '/Selected · in My Bag/'),
 ('test/travelpass.test.mjs', '/Review your journey/', '/Review (&amp;|&) Send/'),
 ('test/access.test.mjs', 'data-cta-in="Continue Your Journey"', 'data-cta-in="Open My Trip"'),
 ('test/access.test.mjs', "Continue Your Journey signed in", "Open My Trip signed in"),
 ('test/efg.test.mjs', '/Your journey is confirmed/', '/Your trip is confirmed/'),
 ('test/efg.test.mjs', '/Your confirmed journey/', '/Your confirmed trip/'),
 ('test/emergency-live.test.mjs', 'Guest: Peggy Berger · G001', 'Guest: Peggy Berger'),
 ('test/emergency-live.test.mjs', '/^Your Journey has been received — SYL-G001-/', '/^Your trip has been received — SYL-G001-/'),
 ('test/emergency-live.test.mjs', "'Your journey has been received'", "'Your trip has been received'"),
 ('test/experiences.test.mjs', "/Add to your journey · ' \\+ money\\(s\\.price\\)/", "/Add to My Bag · ' \\+ money\\(s\\.price\\)/"),
 ('test/experiences.test.mjs', '/not a confirmed reservation/', '/a request, not a reservation/'),
 ('test/flow.test.mjs', '/Your journey is not ready to review yet/', '/Not ready for Review &amp; Send yet/'),
 ('test/journey-draft.test.mjs', 'Your Journey has been received — ', 'Your trip has been received — '),
 ('test/journey-draft.test.mjs', 'Your Journey has been updated — ', 'Your trip has been updated — '),
 ('test/mail-ci.test.mjs', '/Open your journey/', '/Open My Trip/'),
 ('test/mail-ci.test.mjs', '/^SEE YOU IN LAOS — YOUR JOURNEY\\n\\nYour journey has been received\\n\\nDear Sam,/', '/^SEE YOU IN LAOS — MY TRIP\\n\\nYour trip has been received\\n\\nDear Sam,/'),
 ('test/mail-ci.test.mjs', '/Your journey has been updated/', '/Your trip has been updated/'),
 ('test/mail-ci.test.mjs', "'Journey updated — Sam Example · SYL-G777-34DBEFD3'", "'Trip updated — Sam Example · SYL-G777-34DBEFD3'"),
 ('test/mail-ci.test.mjs', '/Journey updated\\n\\nLatest version received', '/Trip updated\\n\\nLatest version received'),
 ('test/mail-ci.test.mjs', '/Status: Updated journey/', '/Status: Updated trip/'),
 ('test/mail-ci.test.mjs', '/Sam Example · G777/', '/Sam Example/'),
 ('test/real-guest-mail.test.mjs', '/Guest: Sam Example · G777\\n/', '/Guest: Sam Example\\n/'),
 ('test/real-guest-mail.test.mjs', "/'✓ Updated journey sent to Guest Relations'/", "/'✓ Updated trip sent to Guest Relations'/"),
 ('test/real-guest-mail.test.mjs', "/'Send updated journey'/", "/'Send Updated Trip'/"),
 ('test/seating-labels.test.mjs', "'CONFIRMED'", "'HELD'"),
 ('test/seating-labels.test.mjs', 'place 17\\nCONFIRMED$/', 'place 17\\nHELD$/'),
 ('test/journey-draft.test.mjs', '/Journey updated\\n\\nLatest version received', '/Trip updated\\n\\nLatest version received'),
 ('src/release-check.cjs', "return 'Fully booked';", "return 'Sold out';"),
 ('docs/acceptance/2026-09-17-p0-empty-bag/e2e.mjs', 'Send updated journey', 'Send Updated Trip'),
 ('test/pricing.test.mjs', "['b2', '<h2>Your journey</h2>']", "['b2', '<h2>My Trip</h2>']"),
 ('test/efg.test.mjs', '/this device cannot tell which version it was/', '/this device cannot tell which copy it was/'),
]
for f, old, new in P:
    p = os.path.join(ROOT, f); s = open(p, encoding='utf8').read(); n = s.count(old)
    if not n and '--rerun' not in sys.argv: sys.exit('MISSING pin: %r in %s' % (old, f))
    if n: open(p, 'w', encoding='utf8').write(s.replace(old, new)); print('%-36s %d  %s' % (f, n, old[:60]))
